# Generated by Django 3.1.3 on 2021-03-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=8)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Obshe Narx')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonmous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism kategoriyasi')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Tovor ismi va malumoti')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naimovinoai')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmlar')),
                ('description', models.TextField(null=True, verbose_name='Opsani')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narx')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diaganol')),
                ('display_type', models.CharField(max_length=255, verbose_name='tip display')),
                ('resolution', models.CharField(max_length=255, verbose_name='Razreshena erkrana')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Obem Batariya')),
                ('ram', models.CharField(max_length=255, verbose_name='Operativka')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Maksimaolniy obem bsravoy pamyatki')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Glavnaya camera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='frontalnaya camera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='kategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naimovinoai')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmlar')),
                ('description', models.TextField(null=True, verbose_name='Opsani')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narx')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diaganol')),
                ('display_type', models.CharField(max_length=255, verbose_name='tip display')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Chastota protsessor')),
                ('ram', models.CharField(max_length=255, verbose_name='Operativka')),
                ('video', models.CharField(max_length=255, verbose_name='Vedio karta')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='vreamiya rabota akumlyator')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='kategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=28, verbose_name='Nomer Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Polizavatel')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Obshe narx')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Korzinka')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Pokipaytel')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Vladelsiya'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
    ]
