# Generated by Django 3.1.3 on 2021-03-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diaganol')),
                ('display_type', models.CharField(max_length=255, verbose_name='tip display')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Chastota protsessor')),
                ('ram', models.CharField(max_length=255, verbose_name='Operativka')),
                ('video', models.CharField(max_length=255, verbose_name='Vedio karta')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='vreamiya rabota akumlyator')),
            ],
            bases=('mainapp.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diaganol')),
                ('display_type', models.CharField(max_length=255, verbose_name='tip display')),
                ('resolution', models.CharField(max_length=255, verbose_name='Razreshena erkrana')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Obem Batariya')),
                ('ram', models.CharField(max_length=255, verbose_name='Operativka')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Maksimaolniy obem bsravoy pamyatki')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Glavnaya camera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='frontalnaya camera')),
            ],
            bases=('mainapp.product',),
        ),
    ]
